### ISSUE TITLE
compile issue Laz ide 3.0

### ISSUE THREAD

**Issue by AndiB74** [PascalCorpsman/ConfigTD#1]
uchunkmanager.pas(866,35) Error: Identifier not found "ssNoDelay"

ssNoDelay is no longer in use see code lNet v0.6.2   

 { TLSocketState }
  TLSocketState = (ssServerSocket, ssBlocking, ssReuseAddress, ssCanSend,
                   ssCanReceive, ssSSLActive{, ssNoDelay});

**Comment by AndiB74** [comment]
Vielleicht SSL fähig machen.

**Comment by PascalCorpsman** [comment]
Das ist ein Bug bei L-Net
Einfach die LNet version von meinem Github Clonen: https://github.com/PascalCorpsman/lnet

**Comment by AndiB74** [comment]
ok dann darf man das nicht von dem OPM installieren denn dann gibt es den Fehler habe Laz 3.0 neu und sauber installiert
