### ISSUE TITLE
Abhängigkeit von Synapse fehlt im Projekt

### ISSUE THREAD

**Issue by AndiB74** [PascalCorpsman/ConfigTD#2]

**Comment by PascalCorpsman** [comment]
?, verstehe die Frage nicht in der Readme.md steht es doch ganz unten dran ..

**Comment by AndiB74** [comment]
ja in der Projektdatei ist aber die Abhängigkeit nicht aufgeführt was auch zu einen kompilierungsfahler bei laz 3.0 (win64) kommt
habe es mit dem Projektinspektor hinzugefügt
