### ISSUE TITLE
Suggestions add Tower attack Animations possibly

### ISSUE THREAD

**Issue by AndiB74** [PascalCorpsman/ConfigTD#4]

**Comment by PascalCorpsman** [comment]
This feature would create a heck of work for a not existing designer..

So you mean a animation that is running as long as the bullet is in the air, or that is played only once when the tower is "creating" the bullet ?

**Comment by AndiB74** [comment]
I mean that a different animation starts before the launch.
I can think of the following: in a missile silo where the hatch opens beforehand
Mage tower that doesn't shoot has rotating mana balls and when it prepares to fire the balls gather and a big mana ball flies to the target.
if the projectile also has an animation it would also be nice (like an enemy animated to the target)

**Comment by PascalCorpsman** [comment]
Ok i get your point, the game logik does not support a "Load weapon" time at the moment.
The Definition at the moment is shot, wait at least X ms until the tower can shoot again, no matter if a opponent is in range or not, to support your suggestion i would need to change this behavior which would break the complete game balancing (or at least all maps would then need to be "rebalanced"). So i have less hopes for that.

Your second request, is already supported, but not yet used (and unfortunatunelly not documented yet). You can use animations for projectiles, buildings, opponents, heros, everything.
The game engine is written in that way, that you can use for all images one of the following
- a .bmp file (clFuchsia is 100% transparent)
- a .png file (uses the alpha channel as dynamic transparency)
- a .ani file which can be created using the animation editor from the bin folder (source and documentation is here https://github.com/PascalCorpsman/Examples/tree/master/OpenGL/Animation_Editor )
